version: '3'
services:
  postgres:
    image: postgres:16.1
    container_name: postgres_container
    environment:
      POSTGRES_DB: analysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  analysis-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analysis-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment: # Definindo variáveis de ambiente para a aplicação
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/analysis
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres


volumes:
  postgres_data:
